@IsTest
private class AccountsTest
{
	// @IsTest
	// static void itShouldUpdateTheOpportunityActivity()
	// {
	// 	// Given a domain with few Account records with an empty description field
	// 	Accounts domain = new Accounts(new List<Account>{	new Account(), new Account(), new Account()	});

	// 	// WHEN we set the description field to a value
	// 	System.Test.startTest();
	// 	domain.updateOpportunityActivity();
	// 	System.Test.stopTest();

	// 	// THEN the description should be updated
	// 	List<Account> result = domain.getAccounts();
	// 	System.assertEquals(3, result.size());
	// 	final String expectedValue = Accounts.OPPORTUNITY_RAISED_DESCRIPTION + ' ' + System.today();
	// 	for (Account record : result)
	// 	{
	// 		System.assertEquals(expectedValue, record.Description);
	// 	}
	// }


}